In [2]:
import pandas as pd

df = pd.read_csv('boston.csv')
# from sklearn.datasets import load_boston
# boston_dataset = load_boston()
# boston_dataset.data
# boston_dataset.data.shape
# boston_dataset.feature_names

# 다항속성
# from sklearn.preprocessing import PolynomialFeatures
# 다항변형기
# polynomial_transformer= PolynomialFeatures(2)
# polynomial_transformer.fit_transform(boston_dataset.data)
# polynomial_feature_names = polynomial_transformer.get_feature_names(boston_dataset.feature_names)
# pd.DataFrame(polynomial_data, columns=polynomial_feature_names)


In [ ]:
# X = pd.DataFrame(diabetes_dataset.data, columns=diabetes_dataset.feature_names)
polynomial_transfomer = PolynomialFeatures(2)
polynomial_features = polynomial_transfomer.fit_transform(diabetes_dataset.data)
features = polynomial_transfomer.get_feature_names(diabetes_dataset.feature_names)
X = pd.DataFrame(polynomial_features, columns=features)



In [3]:
df.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [4]:
X = df.drop(columns=['MEDV'])
X

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [5]:
y = df['MEDV']
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: MEDV, Length: 506, dtype: float64

In [7]:
from sklearn.preprocessing import PolynomialFeatures

polynomial_transformer = PolynomialFeatures(2)

In [14]:
polynomial_data = polynomial_transformer.fit_transform(X)

In [15]:
polynomial_data

array([[1.00000000e+00, 6.32000000e-03, 1.80000000e+01, ...,
        1.57529610e+05, 1.97656200e+03, 2.48004000e+01],
       [1.00000000e+00, 2.73100000e-02, 0.00000000e+00, ...,
        1.57529610e+05, 3.62766600e+03, 8.35396000e+01],
       [1.00000000e+00, 2.72900000e-02, 0.00000000e+00, ...,
        1.54315409e+05, 1.58310490e+03, 1.62409000e+01],
       ...,
       [1.00000000e+00, 6.07600000e-02, 0.00000000e+00, ...,
        1.57529610e+05, 2.23851600e+03, 3.18096000e+01],
       [1.00000000e+00, 1.09590000e-01, 0.00000000e+00, ...,
        1.54802902e+05, 2.54955600e+03, 4.19904000e+01],
       [1.00000000e+00, 4.74100000e-02, 0.00000000e+00, ...,
        1.57529610e+05, 3.12757200e+03, 6.20944000e+01]])

In [16]:
polynomial_data.shape

(506, 105)

In [18]:
polynomial_feature_names = polynomial_transformer.get_feature_names_out(X.columns)
polynomial_feature_names

array(['1', 'CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS',
       'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'CRIM^2', 'CRIM ZN',
       'CRIM INDUS', 'CRIM CHAS', 'CRIM NOX', 'CRIM RM', 'CRIM AGE',
       'CRIM DIS', 'CRIM RAD', 'CRIM TAX', 'CRIM PTRATIO', 'CRIM B',
       'CRIM LSTAT', 'ZN^2', 'ZN INDUS', 'ZN CHAS', 'ZN NOX', 'ZN RM',
       'ZN AGE', 'ZN DIS', 'ZN RAD', 'ZN TAX', 'ZN PTRATIO', 'ZN B',
       'ZN LSTAT', 'INDUS^2', 'INDUS CHAS', 'INDUS NOX', 'INDUS RM',
       'INDUS AGE', 'INDUS DIS', 'INDUS RAD', 'INDUS TAX',
       'INDUS PTRATIO', 'INDUS B', 'INDUS LSTAT', 'CHAS^2', 'CHAS NOX',
       'CHAS RM', 'CHAS AGE', 'CHAS DIS', 'CHAS RAD', 'CHAS TAX',
       'CHAS PTRATIO', 'CHAS B', 'CHAS LSTAT', 'NOX^2', 'NOX RM',
       'NOX AGE', 'NOX DIS', 'NOX RAD', 'NOX TAX', 'NOX PTRATIO', 'NOX B',
       'NOX LSTAT', 'RM^2', 'RM AGE', 'RM DIS', 'RM RAD', 'RM TAX',
       'RM PTRATIO', 'RM B', 'RM LSTAT', 'AGE^2', 'AGE DIS', 'AGE RAD',
       'AGE TAX', 'AGE PTRATIO', 'AGE 

In [20]:
X = pd.DataFrame(polynomial_data, columns=polynomial_feature_names)
X

1     CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  ...  \
0    1.0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  ...   
1    1.0  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  ...   
2    1.0  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  ...   
3    1.0  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  ...   
4    1.0  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  ...   
..   ...      ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  1.0  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  ...   
502  1.0  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  ...   
503  1.0  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  ...   
504  1.0  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  ...   
505  1.0  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  ...   

       TAX^2  TAX PTRATIO      TAX B  TAX LSTAT  PTRATIO^2  PTRATIO B  \
0    87616.0       4528.8  117482.40    1474.08     234.09   6072.570   
1    58564.0       4307.6   96049.80    2211.88     316.84   7064.820   
2    58564.0       4307.6   95064.86     975.26     316.84   6992.374   
3    49284.0       4151.4   87607.86     652.68     349.69   7379.581   
4    49284.0       4151.4   88111.80    1183.26     349.69   7422.030   
..       ...          ...        ...        ...        ...        ...   
501  74529.0       5733.0  107013.27    2639.91     441.00   8231.790   
502  74529.0       5733.0  108353.70    2478.84     441.00   8334.900   
503  74529.0       5733.0  108353.70    1539.72     441.00   8334.900   
504  74529.0       5733.0  107411.85    1769.04     441.00   8262.450   
505  74529.0       5733.0  108353.70    2151.24     441.00   8334.900   

     PTRATIO LSTAT          B^2    B LSTAT  LSTAT^2  
0           76.194  157529.6100  1976.5620  24.8004  
1          162.692  157529.6100  3627.6660  83.5396  
2           71.734  154315.4089  1583.1049  16.2409  
3           54.978  155732.8369  1160.2122   8.6436  
4           99.671  157529.6100  2115.4770  28.4089  
..             ...          ...        ...      ...  
501        203.070  153656.1601  3790.5433  93.5089  
502        190.680  157529.6100  3603.8520  82.4464  
503        118.440  157529.6100  2238.5160  31.8096  
504        136.080  154802.9025  2549.5560  41.9904  
505        165.480  157529.6100  3127.5720  62.0944  

[506 rows x 105 columns]

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)

In [22]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)


(404, 105)
(102, 105)
(404,)
(102,)


In [23]:
model = LinearRegression()


In [24]:
model.fit(X_train, y_train)

LinearRegression()

In [25]:
model.coef_

array([ 2.55996369e-07, -5.09146959e+00, -1.65753983e-01, -5.97358604e+00,
        2.43179259e+01,  1.65180559e+02,  2.19910116e+01,  1.03167123e+00,
       -5.66895775e+00,  3.22443249e+00, -1.10055942e-02,  5.35127787e+00,
       -4.81524409e-02,  7.53109325e-01,  2.16774682e-03,  2.69938772e-01,
        5.87901385e-01,  2.41731932e+00, -2.52413194e-02,  8.92859572e-02,
       -5.18832420e-03, -5.77807152e-02,  3.55602049e-01, -3.86092282e-02,
        5.43572101e-01, -3.18134358e-04,  2.40035425e-02, -7.48850220e-04,
       -7.16133310e-03, -1.06886010e-01, -1.27782609e+00,  2.50137719e-02,
        1.14111417e-04, -1.25254119e-02, -4.68024813e-03,  6.05725185e-04,
       -8.57873132e-03,  1.85030053e-03, -4.64730601e-03,  3.08484808e-02,
       -2.09065897e-01,  1.30035723e+00,  3.13497405e-01,  6.72540163e-04,
        7.51823883e-02, -7.38014889e-03,  4.23364348e-04, -6.72155118e-03,
        6.42107774e-03, -5.32275093e-03,  2.43179261e+01, -1.84845896e+01,
       -6.89090796e+00,  

In [26]:
model.intercept_

np.float64(-141.8985562992178)

In [28]:
y_test_prediction = model.predict(X_test)
y_test_prediction

array([42.00919669, 28.22372855, 25.52688254,  9.05454749, 33.59039809,
       10.49656654, 23.0597188 , 30.35330832, 24.2246103 , 22.30153137,
       33.11791368, 20.74987646, 20.19664017, 32.37012974, 27.35813074,
       20.46264672, 13.68533393, 12.51890372, 15.88730519, 12.47719001,
        3.72827179, 20.49819423, 44.0935012 , 23.31624023, 33.2791559 ,
        9.43400657, 24.71325022, 21.79459244, 24.06481669, 27.42603119,
       15.3289399 ,  6.80742071, 16.76243455, 13.13446141, 25.10746984,
       22.92666537, 29.58310464, 10.66362649, 47.75889196, 35.24353036,
       19.90943076, 15.25028015, 28.15702648, 14.02415348, 26.11171521,
       28.60093424, 15.67989876, 18.96653866, 20.20947991, 14.03412948,
       21.76275323, 22.26202924, 22.01832275, 15.44624876, 15.75821427,
       26.30451802, 40.97147443, 14.50276205, 29.38387137, 21.7344614 ,
       18.72108633, 24.58475299, 14.30971894, 36.2957301 , 26.41019983,
       10.60479846, 16.95708372, 25.40357712, 19.58512193, 23.68

In [29]:
# 평균 제곱근 오차
mean_squared_error(y_test, y_test_prediction) ** 0.5

np.float64(3.1965276513747485)

In [ ]:
# 3200달러 정도 오차가 있다.