In [2]:
import numpy as np



In [3]:
array1 = np.array([1,3,5,6,7,9])
array1


array([1, 3, 5, 6, 7, 9])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(4,17,3)

array([ 4,  7, 10, 13, 16])

In [8]:
type(array1)

numpy.ndarray

In [9]:
array2 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
array1.size # 몇개의 요소가 있는지

6

In [12]:
array2.size

12

In [13]:
array2.shape

(3, 4)

In [15]:
array1.shape

(6,)

In [16]:
gdp_array = np.array([6610, 7637, 8127,8885,10385,12565,13403,12398,8282,10672])
gdp_array[0]

np.int64(6610)

In [17]:
gdp_array[2]

np.int64(8127)

In [19]:
gdp_array[-1]

np.int64(10672)

In [22]:
gdp_array[[1,3,4]]

array([ 7637,  8885, 10385])

In [24]:
array1 = np.array([2,1,3,5])
gdp_array[array1]

array([ 8127,  7637,  8885, 12565])

In [25]:
gdp_array[2:6]

array([ 8127,  8885, 10385, 12565])

In [26]:
gdp_array[0:6]

array([ 6610,  7637,  8127,  8885, 10385, 12565])

In [27]:
gdp_array[:6]

array([ 6610,  7637,  8127,  8885, 10385, 12565])

In [28]:
gdp_array[5:]

array([12565, 13403, 12398,  8282, 10672])

In [29]:
gdp_array[1:8:3]

array([ 7637, 10385, 12398])

In [30]:
gdp_array = np.array([
    [12257,11561,13165,14673,16496,19403],
    [39169,34406,32821,35387,38299,37813],
    [959,1053,1149,1289,1509, 1753],
    [36335,37133,38023,39496,41713,44115]
])

In [31]:
gdp_array

array([[12257, 11561, 13165, 14673, 16496, 19403],
       [39169, 34406, 32821, 35387, 38299, 37813],
       [  959,  1053,  1149,  1289,  1509,  1753],
       [36335, 37133, 38023, 39496, 41713, 44115]])

In [33]:
gdp_array[1][3]

np.int64(35387)

In [37]:
gdp_array[1,3]

np.int64(35387)

In [ ]:
gdp_array[1:3,2:5] # Index1에 있는 1번부터 Index2dp있는 중국까지 받아오고,
# 각 국가에서는 2번 인덱스 부터 4번 까지 받아온다.

In [38]:
gdp_array[1:2, 2:]

array([[32821, 35387, 38299, 37813]])

In [39]:
gdp_array[:,2:5]

array([[13165, 14673, 16496],
       [32821, 35387, 38299],
       [ 1149,  1289,  1509],
       [38023, 39496, 41713]])

In [40]:
gdp_array[1:3,:]

array([[39169, 34406, 32821, 35387, 38299, 37813],
       [  959,  1053,  1149,  1289,  1509,  1753]])

In [42]:
gdp_array = np.array([6610, 7637, 8127,8885,10385,12565,13403,12398,8282,10672])

In [44]:
gdp_array > 10000

array([False, False, False, False,  True,  True,  True,  True, False,
        True])

In [46]:
mask = gdp_array > 10000
gdp_array[mask]

array([10385, 12565, 13403, 12398, 10672])

In [48]:
# 불린 인덱싱
# 마스킹

In [49]:
gdp_array[gdp_array > 10000]

array([10385, 12565, 13403, 12398, 10672])

In [54]:
gdp_array[(gdp_array > 10000) | (gdp_array < 8000)]

array([ 6610,  7637, 10385, 12565, 13403, 12398, 10672])

In [57]:
gdp_array[(gdp_array <= 10000) & (gdp_array >= 8000)]

array([8127, 8885, 8282])

In [58]:
numbers_array = np.arange(1, 101)
numbers_array[numbers_array % 2 == 0]

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [1]:
import numpy as np
gdp_korea_array = np.array([12257, 11561, 13165, 14673, 16496, 19403])


In [2]:
gdp_korea_array.mean()

np.float64(14592.5)

In [3]:
gdp_korea_array.sum()

np.int64(87555)

In [5]:
gdp_korea_array.min()

np.int64(11561)

In [6]:
gdp_korea_array.max()

np.int64(19403)

In [16]:
a = np.array([[1,2,3], [10,12,13]])
print(a)
print(a.sum(axis=0)) ## 쓰지마라
print(a.sum(axis=1)) ## 쓰지마라

print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

[[ 1  2  3]
 [10 12 13]]
[11 14 16]
[ 6 35]
[11 14 16]
[ 6 35]


In [17]:
for i in range(len(gdp_korea_array)):
    gdp_korea_array[i] = gdp_korea_array[i] * 1200

In [19]:
gdp_korea_array = gdp_korea_array * 1200
gdp_korea_array


array([17650080000, 16647840000, 18957600000, 21129120000, 23754240000,
       27940320000])

In [21]:
gdp_us_array = np.array([36335,37133,38023,39496,41713,44115])
gdp_korea_array + gdp_us_array

array([17650116335, 16647877133, 18957638023, 21129159496, 23754281713,
       27940364115])

In [22]:
gdp_korea_array - gdp_us_array

array([17650043665, 16647802867, 18957561977, 21129080504, 23754198287,
       27940275885])

In [23]:
gdp_korea_array * gdp_us_array

array([ 641315656800000,  618184242720000,  720824824800000,
        834515723520000,  990860613120000, 1232587216800000])